on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Publish for Linux x64
      run: dotnet publish -c Release -r linux-x64 -o ./publish/linux-x64 /p:PublishAot=true
    - name: Publish for Linux ARM64
      run: dotnet publish -c Release -r linux-arm64 -o ./publish/linux-arm64 /p:PublishAot=true
    - name: Extract tag name
      id: extract_tag
      run: echo "tag=${{ github.ref_name }}" >> $GITHUB_ENV
    - name: Zip Linux x64 Publish Output
      run: zip -r publish/linux-x64/SharpHolder-${{ env.tag }}-linux-x64.zip publish/linux-x64/
    - name: Zip Linux ARM64 Publish Output
      run: zip -r publish/linux-arm64/SharpHolder-${{ env.tag }}-linux-arm64.zip publish/linux-arm64/
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
    - name: Upload Linux x64 Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./publish/linux-x64/SharpHolder-${{ env.tag }}-linux-x64.zip
        asset_name: SharpHolder-${{ env.tag }}-linux-x64.zip
        asset_content_type: application/zip
    - name: Upload Linux ARM64 Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./publish/linux-arm64/SharpHolder-${{ env.tag }}-linux-arm64.zip
        asset_name: SharpHolder-${{ env.tag }}-linux-arm64.zip
        asset_content_type: application/zip